name: Build APK

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev

    - name: Install Buildozer
      run: pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        buildozer init
        # تحديث ملف التكوين
        echo -e "[app]\ntitle = MyApp\npackage.name = myapp\npackage.domain = org.test\nsource.dir = .\nsource.include_exts = py,png,jpg,kv,atlas\nrequirements = python3==3.10.13,kivy==2.3.0\norientation = portrait\n" > buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: bin/*.apk
